### PR TITLE
Add documentation for tetgen with example gallery

### PR DESCRIPTION
**Pull request by banesullivan**
@akaszynski - if you give me access to the repo after merging these changes, then I can set up the docs to auto build and create a website under https://akaszynski.github.io/tetgen

What the new docs look like on my local machine:

ezgif com-video-to-gif-5

### CODE REVIEW

**Comment by banesullivan** [comment]
@akaszynski - I can't get `tetgen` installed and working on Travis for this PR. Can you check out the build logs when you have a chance?

**Comment by akaszynski** [comment]
Will do once I get it get it working with ``pymeshfix``.

**Comment by akaszynski** [comment]
Just about works.  It just needs ``pyvista`` to be updated to include ``SuperToroid``.

Couldn't manage to figure out why ``pip install .`` wasn't working, so I installed from a wheel instead since ``cibuildwheel`` works.  Also changed the ``tetgen`` import from being relative the docs dir to a system import.

**Comment by banesullivan** [comment]
I changed the PyVista dependency to be the master branch of PyVista on Travis. Then we can set this package up with cron-jobs to make sure it stays compatible with the latest changes in PyVista

**Comment by akaszynski** [comment]
You good to merge?  Thanks for keeping me honest with this module.

**Comment by banesullivan** [comment]
Good to merge from me - can you give me access to this repo so I can set up the auto deployment for the docs?

**Pull request merged**
